
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/ssl-redirect":"false","nginx.ingress.kubernetes.io/use-regex":"true"},"name":"mmwellnessingress","namespace":"nsp-mm-u-member"},"spec":{"rules":[{"host":"uat.aia.com.mm","http":{"paths":[{"backend":{"serviceName":"wellness-web-service","servicePort":4444},"path":"/wellness(/|$)(.*)","pathType":"ImplementationSpecific"},{"backend":{"serviceName":"wellness-api-service","servicePort":8081},"path":"/api(/|$)(.*)","pathType":"ImplementationSpecific"},{"backend":{"serviceName":"hello-world-service","servicePort":8080},"path":"/wwww","pathType":"ImplementationSpecific"}]}}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/session-cookie-path: /wellness(/|$)(.*)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2021-01-09T03:51:28Z"
  generation: 25
  managedFields:
  - apiVersion: networking.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: nginx-ingress-controller
    operation: Update
    time: "2021-01-15T07:18:24Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-01-26T10:47:19Z"
  - apiVersion: networking.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:nginx.ingress.kubernetes.io/affinity: {}
          f:nginx.ingress.kubernetes.io/session-cookie-path: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-25T09:02:09Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/ingress.class: {}
          f:nginx.ingress.kubernetes.io/affinity-mode: {}
          f:nginx.ingress.kubernetes.io/proxy-body-size: {}
          f:nginx.ingress.kubernetes.io/ssl-redirect: {}
          f:nginx.ingress.kubernetes.io/use-regex: {}
      f:spec:
        f:rules: {}
        f:tls: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-05-14T10:47:27Z"
  name: mmwellnessingress
  namespace: nsp-mm-u-member
  resourceVersion: "49567830"
  uid: f3af32a8-f8b0-4521-b36d-8b916ad405c0
spec:
  rules:
  - host: uat.aia.com.mm
    http:
      paths:
      - backend:
          service:
            name: wellness-web-service
            port:
              number: 4444
        path: /wellness(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: wellness-api-service
            port:
              number: 8081
        path: /api(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: hello-world-service
            port:
              number: 8080
        path: /wwww
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - uat.aia.com.mm
    secretName: ingress-nginx-tls-u-mmwellnessingress-v3
status:
  loadBalancer:
    ingress:
    - ip: 10.217.144.7